#!/bin/bash

function print_header() {
  echo "##############################"
  echo $1
  echo "##############################"
}

cd "$HOME"

print_header "Running submodule installs for vim and zsh"

# zsh
~/.zsh/install.sh

# vim 
~/.vim/install.sh


print_header "Installing a few frequent use applications from pacman"
sudo pacman -S remmina freerdp qemu qemu-block-iscsi firefox --noconfirm

print_header "Installing a few frequent use applications from AUR"
yay -S balena-etcher nerd-fonts-hack --noconfirm


