#!/bin/bash

function print_header() {
  echo "##############################"
  echo $1
  echo "##############################"
}

cd "$HOME"

print_header "Running submodule installs for vim and zsh"
# zsh
~/.zsh/install.sh

# vim 
~/.vim/install.sh

